---
title: "FANR8950_Project"
author: "Aurora Fowler"
date: "2025-11-25"
output: html_document
---

# Introduction

### Welcome to my FANR8950 Project! Today we will be walking through a dataset that I collected along the lower Missouri River. This dataset looks at amphibian larvae at different sites and in different wetlands within those sites. 

### Our sampling was stratified to include sites where floodplain restoration has occurred, sites where restoration is slated to occur, and sites with no plans for future restoration. Wetlands are classified into categories. The first category describes where the wetland is in relation to the levee. If the levee is located between the wetland and the mainstem river, that is classified as a "landward" wetland. If the wetland has no levee barrier between it and the mainstem river, that is classified as a "riverward" levee.

### We sampled both naturally occuring wetlands and wetlands that are manmade. If a wetland was constructed it is classified as a "borrow pit" wetland. 